### ISSUE TITLE
Strange addition of space character

### ISSUE THREAD

**Issue by jorgenbuilder** [dfinity/prettier-plugin-motoko#74]
Before formatting
![image](https://user-images.githubusercontent.com/60938577/208502530-f7bf492d-2842-4967-bf9e-c3a180403bee.png)

After formatting
![image](https://user-images.githubusercontent.com/60938577/208502568-e879638b-a00c-4f53-95a9-7523f56ac557.png)

"Full" snippet:

```motoko
assertAllTrue([
  fundedPlan.size() == 1,
  failures.size() == 1,
  fundedPlan[0].2 == 500_000_000_000,
  fundedPlan[0].3 == { e8s = 50_000_000 },
  failures[0].2 == 1_000_000_000_000,
  failures[0].3 == 500_000_000_000,
]);
```

**Comment by rvanasa** [comment]
Wow, this is an amazingly obscure bug related to how the lexer prioritizes tokens. Fixed in `0.2.5`. 

For posterity, this is what was necessary to encounter this corner case:

- A three- or four-letter identifier where the first letter is an `e` or `E`, the second is a number, and the last is another letter
- An expression followed by an integer index followed by this identifier
